version: "3.8"
services:
  app:
    build: .
    depends_on:
      - redis
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DENO_ENV=development
      - REDIS_URL=redis://redis:6379
    command: ["deno", "run", "--watch", "--allow-net", "--allow-env", "main.ts"]
  redis:
    image: "redis/redis-stack"
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_PASSWORD=redis
