version: "3.8"
services:
  app:
    image: ghcr.io/ryangst/url-shortener:latest
    build: .
    depends_on:
      - redis
    ports:
      - "80:8000"
    environment:
      - DENO_ENV=${DENO_ENV:-production}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis}
    command: ["deno", "run", "--allow-net", "--allow-env", "main.ts"]
    restart: unless-stopped
    deploy:
      update_config:
        order: start-first
  redis:
    image: "redis/redis-stack"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: ["redis-server", "--requirepass ${REDIS_PASSWORD:-redis}"]

volumes:
  redis_data:
