version: "3.8"
services:
  app:
    image: ghcr.io/ryangst/url-shortener:${GIT_TAG:-latest}
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - redis
    ports:
      - 8000:8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`url.ryanmac.dev`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=myresolver"
      - "traefik.http.routers.app.service=app"
      - "traefik.http.services.app.loadbalancer.server.port=8000"
    environment:
      - DENO_ENV=${DENO_ENV:-production}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis}
    command: [
      "deno",
      "run",
      "--allow-net",
      "--allow-read",
      "--allow-env",
      "main.ts",
    ]
    restart: unless-stopped
    deploy:
      update_config:
        order: start-first
  redis:
    image: "redis/redis-stack"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: ["redis-server", "--requirepass ${REDIS_PASSWORD:-redis}"]

volumes:
  redis_data:
  letsencrypt:
