# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will use Docker Compose to run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno CI with Docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      # Remove the Setup Deno step, as Deno is inside the container
      # - name: Setup Deno
      #   uses: denoland/setup-deno@v2
      #   with:
      #     deno-version: v2.x

      # Optional: Build the Docker image(s) if needed explicitly
      # - name: Build Docker Images
      #   run: docker-compose build app # Build only the app service if needed

      # Run linter using docker-compose
      - name: Run linter
        run: docker compose run --rm app deno lint

      # Run tests using docker-compose with specified permissions
      - name: Run tests
        run: docker compose run --rm app deno test --allow-net --allow-read --allow-env
